### ISSUE TITLE
Include a usage example for the session scoped fixture

### ISSUE THREAD

**Issue by jong-eatsa** [ClearcodeHQ/pytest-dynamodb#29]
The usage example for the client/resource fixture ```dynamodb``` is well-documented [here](https://github.com/ClearcodeHQ/pytest-dynamodb/blob/master/tests/test_dynamodb.py).

Please also include one for the session scoped fixture ```dynamodb_proc ```. Current it returns a ```TCPExecutor()``` object, and I cannot perform any table/resource/client operations such as .create_table() as it is not a boto3 table resource.

I need a session-scoped wrapper around the dynamodb instance. I tried to something like
```
@pytest.fixture(scope='module')
def dynamodb_table(dynamodb):
	# create the DynamoDB table
	table = dynamodb.create_table(...)

       # create abstraction layer / wrapper around table with a custom class
       table_wrapper = CustomDynamodbTable(...)

       # use table_wrapper instead of table
       yield table_wrapper

       # clean up
       table.delete()

def test_some_fn(dynamodb_table):
      # use table
      dynamodb_table.put_item(...)
```

which returned an error:
```
ScopeMismatch: You tried to access the 'function' scoped fixture 'dynamodb' with a 'module' scoped request object, involved factories
```

Do I need to do something like this?
```
@pytest.fixture(scope='module')
def dynamodb_table(dynamodb_proc):
	# create the DynamoDB table
	table = dynamodb_proc.create_table(...)???
```

**Comment by fizyk** [comment]
Hi,

The _proc is always about the process, so this fixture allows you to manage the process itself, not the database there. It's session scoped to actually make the tests faster, as otherwise you'd have to start and stop it each test. So your fixture would actually have to make connection itself to the said process. See here: https://github.com/ClearcodeHQ/pytest-dynamodb/blob/master/src/pytest_dynamodb/factories.py#L126

Now the dynamodb fixture is function scoped, because each test should begin with known same state. session scoped fixture like that might case one test to influence other tests which will make them non deterministic.

To overcome this, you'd actually have to create another function fixture to clean up, or have each test to clean after itself. I usually find that hard to maintain.

**Comment by jong-eatsa** [comment]
Hi, thanks for the quick reply.

Currently my fixture ```dynamodb_table``` indeed handles the clean up (see code after ```yield```), and each of my test functions cleans up after itself. This keeps the boilerplate of declaring the .create_table() and the wrapper class associated with it for each test in the fixture.

Could you give me a quick example / gist of how to set up a database within the process? I'm not sure how to make use of [L126 in factories.py](https://github.com/ClearcodeHQ/pytest-dynamodb/blob/master/src/pytest_dynamodb/factories.py#L126).

**Comment by fizyk** [comment]
See [L137](https://github.com/ClearcodeHQ/pytest-dynamodb/blob/master/src/pytest_dynamodb/factories.py#L137)

However note that leaving tests to clean up after themselves might be tricky, if one test fails in the middle, it won't clean after itself, making other test fail afterwards. Instead of one, you'd have few more tests to take care of.

Why do you need a module scope for the table anyway?
Personally I'd create something like, if I wanted to get a custom wrapper on the table in tests:

```
@pytest.fixture
def dynamodb_table(dynamodb):
	# create the DynamoDB table
	table = dynamodb.create_table(...)

       # create abstraction layer / wrapper around table with a custom class
       table_wrapper = CustomDynamodbTable(...)

       # use table_wrapper instead of table
       return table_wrapper
```

dynamodb takes care of all the cleaning each test, so no problem with failed test that won't clean after themselves.

**Comment by jong-eatsa** [comment]
I couldn't make use of the function-scoped `dynamodb`, but I was able to make `dynamodb_proc` work. I applied it in a module-scoped fixture that used boto3 to create tables, and this fixture was used in each of the test functions where I defined the custom DynamoDB wrapper class.

Thanks for your help!
